# -*- coding: utf-8 -*-
"""DFS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtFu8DfoKY5LyfSWNJos1LRRs8BdVZxc
"""

import time

def dfs(grafo, nodo, visitados=None):
    """
    Implementación del algoritmo Depth-First Search (DFS).

    Parámetros:
    grafo: diccionario que representa el grafo (lista de adyacencia)
    nodo: nodo inicial desde donde comienza la búsqueda
    visitados: conjunto de nodos ya visitados

    Retorna:
    conjunto de nodos visitados
    """

    if visitados is None:
        visitados = set()

    # Marcar nodo como visitado
    visitados.add(nodo)
    print(nodo, end=" ")

    # Explorar vecinos
    for vecino in grafo.get(nodo, []):
        if vecino not in visitados:
            dfs(grafo, vecino, visitados)

    return visitados


def ejecutar_dfs(grafo, inicio):
    """
    Ejecuta DFS y mide el tiempo de ejecución.
    """

    inicio_tiempo = time.time()

    visitados = dfs(grafo, inicio)

    fin_tiempo = time.time()

    print("\n")
    print("Nodos visitados:", visitados)
    print("Tiempo de ejecución:", fin_tiempo - inicio_tiempo, "segundos")


# Ejemplo de grafo
grafo = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

ejecutar_dfs(grafo, 'A')