# -*- coding: utf-8 -*-
"""DFS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtFu8DfoKY5LyfSWNJos1LRRs8BdVZxc
"""

import time

def dfs(grafo, nodo, visitados=None):
    """
    Implementación del algoritmo Depth-First Search (DFS).

    Parámetros:
    grafo: diccionario que representa el grafo (lista de adyacencia)
    nodo: nodo inicial desde donde comienza la búsqueda
    visitados: conjunto de nodos ya visitados

    Retorna:
    conjunto de nodos visitados
    """

    if visitados is None: #Si no hay ningun nodo visitado, se crea el conjunto de nodos visitados
        visitados = set()

    # Marcar nodo como visitado
    visitados.add(nodo)
    print(nodo, end=" ")

    #Explora vecinos
    for vecino in grafo.get(nodo, []):
        if vecino not in visitados:
            dfs(grafo, vecino, visitados) #Se llama recursivamente dfs haciendo bactraking para explorar profundamente

    return visitados #Devuelve le conunto de nodos visitados en orden


# Ejemplo de grafo
grafo = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

inicio_tiempo = time.time()

print("Recorrido DFS:")
dfs(grafo, 'A')

fin_tiempo = time.time()

print("\n")
print("Tiempo de ejecución:", fin_tiempo - inicio_tiempo, "segundos")