# -*- coding: utf-8 -*-
"""Ocho reynas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D__-GvcH7dx3-6zBiqZx9dr3Ql5J3d4y
"""

import time

N = 8 #Constante global

def es_seguro(tablero, fila, columna):
    """
    Verifica si es seguro colocar una reina en la posición (fila, columna)
    Return: True si es seguro, False en caso contrario
    """

    # Revisar fila hacia la izquierda
    for i in range(columna):
        if tablero[fila][i] == 1:
            return False

    # Revisar diagonal superior izquierda
    i, j = fila, columna
    while i >= 0 and j >= 0:
        if tablero[i][j] == 1:
            return False
        i -= 1
        j -= 1

    # Revisar diagonal inferior izquierda
    i, j = fila, columna
    while i < N and j >= 0:
        if tablero[i][j] == 1:
            return False
        i += 1
        j -= 1

    return True


def resolver_reinas(tablero, columna):
    """
    Implementa el algoritmo de Backtracking para resolver el problema
    de las 8 reinas colocando una reina por columna

    Return: True si se encuentra una solución, False en caso contrario
    """

    # Caso base: todas las reinas colocadas
    if columna >= N:
        return True

    # Probar todas las filas de la columna actual
    for fila in range(N):

        if es_seguro(tablero, fila, columna):

            tablero[fila][columna] = 1

            if resolver_reinas(tablero, columna + 1):
                return True

            # Backtracking
            tablero[fila][columna] = 0

    return False


def imprimir_tablero(tablero):
    """
    Imprime el tablero mostrando las reinas con 'Q'
    y espacios vacíos con '.'
    Return: None
    """
    print("\nSolución encontrada:\n")

    for fila in tablero:
        for celda in fila:
            if celda == 1:
                print("R", end=" ")
            else:
                print(".", end=" ")
        print()


def ocho_reinas():
    """
    Función principal que inicializa el tablero,
    ejecuta el algoritmo y mide el tiempo de ejecución.

    Return: None
    """

    tablero = [[0 for _ in range(N)] for _ in range(N)]

    inicio = time.time()

    if resolver_reinas(tablero, 0):
        imprimir_tablero(tablero)
    else:
        print("No existe solución.")

    fin = time.time()

    print(f"\nTiempo de ejecución: {fin - inicio:.6f} segundos")


if __name__ == "__main__":
  """
  Ejecuta la función principal del programa.
  """
  ocho_reinas()